server:
  port: 9092

spring:
  application:
    name: evan-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test_admin_upin7_com?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: wedding
    password: Wedding123456


jwt:
  secret: qnAqsQa7600vrTBcr1WB8P8dg4cbgS5i8LZGjWnpREL # 密钥
  expiration: 30 # token 有效期（S)

logging:
  file:
    path: /Users/yuzhiwen/Desktop/www/java/evan-test/logs
